munoz-common-web-faces/src/main/java/hu/pe/munoz/commonwebfaces/bean/ApplicationBean.java
package hu.pe.munoz.commonwebfaces.bean;

import static hu.pe.munoz.common.helper.CommonConstants.SYSTEM_KEY_IMAGE;
import static hu.pe.munoz.common.helper.CommonConstants.SYSTEM_KEY_LANGUAGE_CODE;
import static hu.pe.munoz.common.helper.CommonConstants.SYSTEM_KEY_ONLINE;
import static hu.pe.munoz.common.helper.CommonConstants.SYSTEM_KEY_TEMPLATE_CODE;

import java.io.Serializable;
import java.util.Locale;
import java.util.ResourceBundle;

import javax.annotation.PostConstruct;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import hu.pe.munoz.common.helper.CommonConstants;
import hu.pe.munoz.common.helper.HttpClient;
import hu.pe.munoz.common.helper.HttpClientResponse;

@ManagedBean
@ApplicationScoped
public class ApplicationBean implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private static final Logger LOG = LoggerFactory.getLogger(ApplicationBean.class);

    private JSONArray systems;
    private Locale locale;
    private String languageCode;
    private String templateCode;
    private String image;
    private String online;

    protected ResourceBundle applicationBundle = ResourceBundle.getBundle("application");
    private String hostUrl;

    @PostConstruct
    public void postConstruct() {
        LOG.debug("Post construct ApplicationBean ...");
        hostUrl = applicationBundle.getString("rest.HostUrl");

        try {
            HttpClientResponse response = new HttpClient()
                    .setHost(hostUrl)
                    .setPath("/settings/system/list")
                    .get();
            if (response != null) {

                if (CommonConstants.SUCCESS.equals(response.getStatus())) {
                    setSystems((JSONArray) response.getData());
                } else {
                    LOG.error(response.getMessage());
                }
            }
        } catch (Exception e) {
            LOG.error(e.toString(), e);
        }
    }

    public JSONArray getSystems() {
        return this.systems;
    }

    public void setSystems(JSONArray systems) {
        this.systems = systems;
        for (Object o : systems) {

            JSONObject json = (JSONObject) o;
            String key = (String) json.get("dataKey");
            String value = (String) json.get("dataValue");

            if (SYSTEM_KEY_LANGUAGE_CODE.equals(key)) {
                languageCode = value;
                locale = new Locale(languageCode);
            } else if (SYSTEM_KEY_TEMPLATE_CODE.equals(key)) {
                templateCode = value;
            } else if (SYSTEM_KEY_ONLINE.equals(key)) {
                online = value;
            } else if (SYSTEM_KEY_IMAGE.equals(key)) {
                image = value;
            }
        }
    }

    public Locale getLocale() {
        return locale;
    }

    public void setLocale(Locale locale) {
        this.locale = locale;
    }

    public String getLanguageCode() {
        return languageCode;
    }

    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }

    public String getTemplateCode() {
        return templateCode;
    }

    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getOnline() {
        return online;
    }

    public void setOnline(String online) {
        this.online = online;
    }

    public String getApplicationName() {
        return applicationBundle.getString("application.info.Name");
    }

    public String getApplicationVersion() {
        return applicationBundle.getString("application.info.Version");
    }

}

munoz-common-web-faces/src/main/java/hu/pe/munoz/commonwebfaces/bean/DashboardBean.java
package hu.pe.munoz.commonwebfaces.bean;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean
@ViewScoped
public class DashboardBean implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    
}

munoz-common-web-faces/src/main/java/hu/pe/munoz/commonwebfaces/bean/DefaultBehaviorBean.java
package hu.pe.munoz.commonwebfaces.bean;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import javax.faces.bean.ManagedProperty;

import org.omnifaces.util.Faces;

import hu.pe.munoz.commonwebfaces.helper.PageMode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public abstract class DefaultBehaviorBean extends HttpClientBean {

    private static final Logger LOG = LoggerFactory.getLogger(DefaultBehaviorBean.class);

    private static final List<String> LIST_PATH_FOR_VIEW = Arrays.asList("/index.xhtml", "/index", "/view.xhtml", "/view");
    private static final List<String> LIST_PATH_FOR_MODIFY = Arrays.asList("/edit.xhtml", "/edit", "/add.xhtml", "/add");

    private static final List<String> PATH_INDEX = Arrays.asList("/index.xhtml", "/index");

    @ManagedProperty(value = "#{loginBean}")
    protected LoginBean loginBean;

    public void setLoginBean(LoginBean loginBean) {
        this.loginBean = loginBean;
    }

    protected int mode = PageMode.INDEX;

    public DefaultBehaviorBean() {
        if (Faces.getFlash().get("mode") != null) {
            mode = (Integer) Faces.getFlash().get("mode");
        }
    }

    public void pageCheck() {
        String path = Faces.getRequestServletPath();
        String pathFirstPart = path.substring(1, path.lastIndexOf("/"));
        String pathLastPart = path.substring(path.lastIndexOf("/"));
        if (!PATH_INDEX.contains(pathLastPart) && mode == PageMode.INDEX) { // Page mode is not set yet, so it is PageMode.INDEX
            try {
                Faces.redirect(pathFirstPart + "/index.xhtml");
            } catch (IOException e) {
                LOG.error(e.toString(), e);
            }
            return;
        }
        if (LIST_PATH_FOR_MODIFY.contains(pathLastPart)) {
            if (!isModifyAllowed()) {
                try {
                    Faces.getExternalContext().dispatch("error.xhtml"); // Forwards to error page (browser's URL is not changed)
                } catch (IOException e) {
                    LOG.error(e.toString(), e);
                }
                return;
            }
        }
        if (LIST_PATH_FOR_VIEW.contains(pathLastPart)) {
            if (!isViewAllowed()) {
                try {
                    Faces.getExternalContext().dispatch("error.xhtml"); // Forwards to error page (browser's URL is not changed)
                } catch (IOException e) {
                    LOG.error(e.toString(), e);
                }
                return;
            }
        }
    }

    public String gotoEdit() {
        Faces.getFlash().put("mode", PageMode.EDIT);
        return "edit?faces-redirect=true";
    }

    public String gotoAdd() {
        Faces.getFlash().put("mode", PageMode.ADD);
        return "add?faces-redirect=true";
    }

    public String gotoIndex() {
        Faces.getFlash().put("mode", PageMode.INDEX);
        return "index?faces-redirect=true";
    }

    public boolean isViewAllowed() {
        return loginBean.isViewAllowed(getMenuCode());
    }

    public boolean isModifyAllowed() {
        return loginBean.isModifyAllowed(getMenuCode());
    }

    abstract protected String getMenuCode();

}

munoz-common-web-faces/src/main/java/hu/pe/munoz/commonwebfaces/bean/HttpClientBean.java
package hu.pe.munoz.commonwebfaces.bean;

import hu.pe.munoz.common.helper.HttpClient;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedProperty;

import java.util.ResourceBundle;
import org.json.simple.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public abstract class HttpClientBean {

    private static final Logger LOG = LoggerFactory.getLogger(HttpClientBean.class);
    
    protected ResourceBundle applicationBundle = ResourceBundle.getBundle("application");
    protected String hostUrl;

    @ManagedProperty(value = "#{applicationBean}")
    protected ApplicationBean applicationBean;

    public void setApplicationBean(ApplicationBean applicationBean) {
        this.applicationBean = applicationBean;
    }

    @PostConstruct
    protected void initialize() {
        LOG.debug("Initialize {} ...", getClass()); 
        hostUrl = applicationBundle.getString("rest.HostUrl");
        postConstruct();
    }

    abstract protected void postConstruct();
    
    protected HttpClient getHttpClient() {
        return new HttpClient().setHeader("Accept-Language", applicationBean.getLanguageCode());
    }

    protected HttpClient getHttpClient(String host, String path) {
        return new HttpClient()
                .setHost(host)
                .setPath(path)
                .setHeader("Accept-Language", applicationBean.getLanguageCode());
    }

    protected HttpClient getHttpClient(String host, String path, JSONObject parameters) {
        return new HttpClient()
                .setHost(host)
                .setPath(path)
                .setParameters(parameters)
                .setHeader("Accept-Language", applicationBean.getLanguageCode());
    }

}

munoz-common-web-faces/src/main/java/hu/pe/munoz/commonwebfaces/bean/MenuBean.java
package hu.pe.munoz.commonwebfaces.bean;

import java.io.File;
import java.io.FileFilter;
import java.io.FileReader;
import java.io.IOException;
import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@ManagedBean
@SessionScoped
public class MenuBean implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private static final Logger LOG = LoggerFactory.getLogger(MenuBean.class);
    
    private static final String POSTFIX_FILE_MENU = ".menu.json";

    private static final String POSTFIX_FILE_SUBMENU = ".submenu.json";

    private JSONArray menus;
    private JSONArray flatMenus;

    @PostConstruct
    public void init() {
        loadMenus();
    }

    @SuppressWarnings("unchecked")
    private void loadMenus() {
        String dir = FacesContext.getCurrentInstance().getExternalContext().getRealPath("/WEB-INF/");
        
        File[] menuFiles = new File(dir).listFiles(new FileFilter() {

            public boolean accept(File file) {
                String fileName = file.getName().toLowerCase();
                return fileName.endsWith(POSTFIX_FILE_MENU);
            }
        });

        File[] submenuFiles = new File(dir).listFiles(new FileFilter() {
            
            public boolean accept(File file) {
                String fileName = file.getName().toLowerCase();
                return fileName.endsWith(POSTFIX_FILE_SUBMENU);
            }
        });

        menus = new JSONArray();
        flatMenus = new JSONArray();
        JSONParser parser = new JSONParser();
        try {
            for (File file : menuFiles) {
                JSONArray array = (JSONArray) parser.parse(new FileReader(file));
                menus.addAll(array);
            }
            JSONArray submenus = new JSONArray();
            for (File file : submenuFiles) {
                JSONArray array = (JSONArray) parser.parse(new FileReader(file));
                submenus.addAll(array);
            }
            for (Object menu : menus) {
                JSONObject json = (JSONObject) menu;
                String parentCode = (String) json.get("code");
                JSONArray children = getChildren(submenus, parentCode);
                json.put("submenus", children);
                flatMenus.add(json);
                flatMenus.addAll(children);
            }
        } catch (IOException e) {
            LOG.error(e.getMessage(), e);
        } catch (ParseException e) {
            LOG.error(e.getMessage(), e);
        }
    }

    @SuppressWarnings("unchecked")
    public JSONArray getChildren(JSONArray submenus, String parentCode) {
        JSONArray children = new JSONArray();
        for (int i = 0; i < submenus.size(); i++) {
            JSONObject json = (JSONObject) submenus.get(i);
            if (parentCode.equals(json.get("parentCode"))) {
                children.add(json);
            }
        }
        return children;
    }
    
    public JSONArray getMenus() {
        return menus;
    }

    public JSONArray getFlatMenus() {
        return flatMenus;
    }

}

munoz-common-web-faces/src/main/java/hu/pe/munoz/commonwebfaces/servlet/ImageServlet.java
package hu.pe.munoz.commonwebfaces.servlet;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ResourceBundle;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@WebServlet("/resources.image/*")
public class ImageServlet extends HttpServlet {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private static final Logger LOG = LoggerFactory.getLogger(ImageServlet.class);

    protected ResourceBundle applicationBundle = ResourceBundle.getBundle("application");
    
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        try {
            String imagesDir = applicationBundle.getString("directory.path.Images");
            String filename = req.getPathInfo().substring(1);
            
            File file = new File(imagesDir, filename);
            resp.setHeader("Content-Type", getServletContext().getMimeType(filename));
            resp.setHeader("Content-Length", String.valueOf(file.length()));
            resp.setHeader("Content-Disposition", "inline; filename=\"" + filename + "\"");
            Files.copy(file.toPath(), resp.getOutputStream());
        } catch (Exception e) {
            LOG.error(e.toString(), e);
        }
    }

}

munoz-common-web-faces/src/main/webapp/dashboard.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/templates/includes/layout.xhtml" 
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core" >

    <ui:define name="title">#{lang['title.Dashboard']}</ui:define>

    <ui:define name="inner">

    </ui:define>

</ui:composition>

munoz-common-web-faces/src/main/webapp/error.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <f:view locale="#{applicationBean.locale}">
        <h:head>
            <f:facet name="first">
                <meta charset="utf-8" />
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
                <link rel="icon" href="favicon.ico" />
            </f:facet>
            <h:outputStylesheet library="common" name="css/common.css" />
            <title>#{lang['title.Error']}</title>
        </h:head>

        <h:body>
            <h:form id="logout-form">
                <p:outputPanel>
                    <div class="ui-grid ui-grid-responsive">
                        <div class="ui-grid-row"
                             style="padding: 10px; background: #79c9ec;">
                            <div class="ui-grid-col-4">
                                <h:outputLink value="#{request.contextPath}">
                                    <p:graphicImage value="/resources.image/#{applicationBean.image}" height="30px" style="vertical-align: middle;" />
                                </h:outputLink>
                            </div>
                            <div class="ui-grid-col-4" style="line-height: 30px;"></div>
                            <div class="ui-grid-col-4" style="line-height: 30px;"></div>
                        </div>
                        <div class="ui-grid-row"
                             style="padding-top: 100px; padding-bottom: 100px; background: #79c9ec;">
                            <div class="ui-grid-col-4"></div>
                            <div class="ui-grid-col-4" style="background: #eee; padding: 6px 0; border-top: 4px solid #0078ae;">
                                <div class="ui-fluid">
                                    <p:panelGrid columns="1" columnClasses="ui-grid-col-12" layout="grid" styleClass="ui-panelgrid-blank">
                                        <h1 class="page-title" style="margin-bottom: 5px; text-transform: uppercase;">#{lang['title.Error']}</h1>
                                        <h:outputText value="#{lang['label.PageErrorMessage']}" escape="false" />
                                        <p:commandButton value="#{lang['button.BackToDashboard']}" action="dashboard?faces-redirect=true" />
                                    </p:panelGrid>
                                </div>
                            </div>
                            <div class="ui-grid-col-4"></div>
                        </div>
                        <div class="ui-grid-row footer" >
                            <div class="ui-grid-col-4">
                                <h:outputText value="#{applicationBean.applicationName} #{applicationBean.applicationVersion}" styleClass="text-version" />
                            </div>
                            <div class="ui-grid-col-4" style="text-align: center">

                            </div>
                            <div class="ui-grid-col-4"></div>
                        </div>
                    </div>
                </p:outputPanel>
            </h:form>
        </h:body>
    </f:view>
</html>

munoz-common-web-faces/src/main/webapp/index.jsp
<% 
    /**
     * This page is intended to fix the login filter not executed issue.
     * 
     * If we set the <welcome-file> in web.xml with login.xhtml,
     * then when we open localhost:8080/common-webapp/ in a browser, 
     * the site content will be the login page from login.xhtml file,
     * but the url did not change to localhost:8080/common-webapp/login.xhtml 
     * which is causing the login filter did not get executed.
     * 
     * This index.jsp will do a full redirect to login.xhtml page 
     * so the url will change to localhost:8080/common-webapp/login.xhtml
     * and the login filter will get executed.
     */
    response.sendRedirect("login.xhtml"); 
%>

munoz-common-web-faces/src/main/webapp/login.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <f:view locale="#{applicationBean.locale}">
        <h:head>
            <f:facet name="first">
                <meta charset="utf-8" />
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
                <link rel="icon" href="favicon.ico" />
            </f:facet>
            <h:outputStylesheet library="common" name="css/common.css" />
            <title>#{lang['title.Login']}</title>
        </h:head>

        <h:body>
            <h:form id="loginForm">
                <p:outputPanel>
                    <div class="ui-grid ui-grid-responsive">
                        <div class="ui-grid-row" style="padding: 10px; background: #79c9ec;">
                            <div class="ui-grid-col-4">
                                <h:outputLink value="#{request.contextPath}">
                                    <p:graphicImage value="/resources.image/#{applicationBean.image}" height="30px" style="vertical-align: middle;" />
                                </h:outputLink>
                            </div>
                            <div class="ui-grid-col-4" style="line-height: 30px;"></div>
                            <div class="ui-grid-col-4" style="line-height: 30px;"></div>
                        </div>
                        <div class="ui-grid-row"
                             style="padding-top: 100px; padding-bottom: 100px; background: #79c9ec;">
                            <div class="ui-grid-col-4"></div>
                            <div class="ui-grid-col-4">
                                <p:messages id="messages" closable="true" />
                                <div class="ui-fluid" style="background: #eee; padding: 6px 0; border-top: 4px solid #0078ae;">
                                    <p:panelGrid columns="1" columnClasses="ui-grid-col-12" layout="grid" styleClass="ui-panelgrid-blank">
                                        <h1 class="page-title" style="margin-bottom: 5px; text-transform: uppercase;">#{lang['title.Login']}</h1>
                                        <p:inputText id="username" value="#{loginBean.inputUsername}" placeholder="#{lang['label.UsernameEmail']}" required="true" requiredMessage="#{lang['required.UsernameEmailCannotBeEmpty']}" />
                                        <p:password id="password" value="#{loginBean.inputPassword}" placeholder="#{lang['label.Password']}" required="true" requiredMessage="#{lang['required.PasswordCannotBeEmpty']}" />
                                        <p:commandButton value="#{lang['button.Login']}" actionListener="#{loginBean.doLogin()}" update=":loginForm" />
                                    </p:panelGrid>
                                </div>
                            </div>
                            <div class="ui-grid-col-4"></div>
                        </div>

                        <div class="ui-grid-row footer" >
                            <div class="ui-grid-col-4">
                                <h:outputText value="#{applicationBean.applicationName} #{applicationBean.applicationVersion}" styleClass="text-version" />
                            </div>
                            <div class="ui-grid-col-4" style="text-align: center">

                            </div>
                            <div class="ui-grid-col-4"></div>
                        </div>
                    </div>
                </p:outputPanel>
            </h:form>
        </h:body>
    </f:view>
</html>

munoz-common-web-faces/src/main/webapp/logout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <f:view locale="#{applicationBean.locale}">
        <h:head>
            <f:facet name="first">
                <meta charset="utf-8" />
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
                <link rel="icon" href="favicon.ico" />
            </f:facet>
            <h:outputStylesheet library="common" name="css/common.css" />
            <title>#{lang['title.Logout']}</title>
        </h:head>

        <h:body>
            <h:form id="logout-form">
                <p:outputPanel>
                    <div class="ui-grid ui-grid-responsive">
                        <div class="ui-grid-row"
                             style="padding: 10px; background: #79c9ec;">
                            <div class="ui-grid-col-4">
                                <h:outputLink value="#{request.contextPath}">
                                    <p:graphicImage value="/resources.image/#{applicationBean.image}" height="30px" style="vertical-align: middle;" />
                                </h:outputLink>
                            </div>
                            <div class="ui-grid-col-4" style="line-height: 30px;"></div>
                            <div class="ui-grid-col-4" style="line-height: 30px;"></div>
                        </div>
                        <div class="ui-grid-row"
                             style="padding-top: 100px; padding-bottom: 100px; background: #79c9ec;">
                            <div class="ui-grid-col-4"></div>
                            <div class="ui-grid-col-4" style="background: #eee; padding: 6px 0; border-top: 4px solid #0078ae;">
                                <div class="ui-fluid">
                                    <p:panelGrid columns="1" columnClasses="ui-grid-col-12" layout="grid" styleClass="ui-panelgrid-blank">
                                        <h1 class="page-title" style="margin-bottom: 5px; text-transform: uppercase;">#{lang['title.Logout']}</h1>
                                        <h:outputText value="#{lang['label.LogoutSuccessMessage']}" />
                                        <p:commandButton value="#{lang['button.BackToLogin']}" action="login?faces-redirect=true" />
                                    </p:panelGrid>
                                </div>
                            </div>
                            <div class="ui-grid-col-4"></div>
                        </div>

                        <div class="ui-grid-row footer" >
                            <div class="ui-grid-col-4">
                                <h:outputText value="#{applicationBean.applicationName} #{applicationBean.applicationVersion}" styleClass="text-version" />
                            </div>
                            <div class="ui-grid-col-4" style="text-align: center">

                            </div>
                            <div class="ui-grid-col-4"></div>
                        </div>
                    </div>
                </p:outputPanel>
            </h:form>
        </h:body>
    </f:view>
</html>